# Generated by Django 5.2.18 on 2026-10-08 20:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('horario', models.TimeField(verbose_name='horário')),
                ('ativo', models.BooleanField(default=True, verbose_name='oferecer este horário')),
            ],
            options={
                'verbose_name': 'horário disponível',
                'verbose_name_plural': 'horários disponíveis',
                'ordering': ['data', 'horario', 'profissional__nome', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='disponibilidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agenda.disponibilidade'),
        ),
        migrations.CreateModel(
            name='FichaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='idade')),
                ('contato', models.CharField(max_length=120, verbose_name='contato')),
                ('tem_problemas_saude', models.BooleanField(verbose_name='tem problemas de saúde')),
                ('problemas_saude', models.TextField(blank=True, max_length=2000, verbose_name='quais problemas de saúde')),
                ('usa_medicacoes', models.BooleanField(verbose_name='usa medicações')),
                ('medicacoes', models.TextField(blank=True, max_length=2000, verbose_name='quais medicações')),
                ('ultimos_exames', models.CharField(blank=True, max_length=200, verbose_name='última vez que fez exames')),
                ('motivo_consulta', models.TextField(max_length=2000, verbose_name='motivo da consulta')),
                ('observacoes', models.TextField(blank=True, max_length=2000, verbose_name='observações')),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='agenda.agendamento')),
            ],
            options={
                'verbose_name': 'ficha do paciente',
                'verbose_name_plural': 'fichas dos pacientes',
            },
        ),
        migrations.CreateModel(
            name='FormularioAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(default='Agendamento nutricional', max_length=150, verbose_name='título')),
                ('descricao', models.TextField(blank=True, max_length=2000, verbose_name='mensagem de apresentação')),
                ('ativo', models.BooleanField(default=True, verbose_name='disponível para pacientes')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulário de agendamento',
                'verbose_name_plural': 'formulários de agendamento',
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='agenda.formularioagendamento'),
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome do nutricionista')),
                ('crn', models.CharField(blank=True, max_length=30, verbose_name='CRN')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissionais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'nutricionista',
                'verbose_name_plural': 'nutricionistas',
                'ordering': ['nome', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disponibilidades', to='agenda.profissional', verbose_name='nutricionista'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agenda.profissional', verbose_name='nutricionista da consulta'),
        ),
        migrations.AddConstraint(
            model_name='agendamento',
            constraint=models.UniqueConstraint(condition=models.Q(('profissional__isnull', False), models.Q(('status', 'cancelado'), _negated=True)), fields=('profissional', 'data', 'horario'), name='unique_active_professional_booking', violation_error_message='Este nutricionista já possui um agendamento nesse horário.'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidade',
            constraint=models.UniqueConstraint(fields=('profissional', 'data', 'horario'), name='unique_professional_availability', violation_error_message='Este nutricionista já tem esse horário cadastrado em um formulário.'),
        ),
    ]
