# Generated by Django 5.2.18 on 2026-10-08 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_fichapaciente_respostas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelado em'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='concluído em'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, max_length=2000, verbose_name='motivo do cancelamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('confirmado', 'Confirmado'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], default='confirmado', max_length=12, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='AlteracaoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior', models.CharField(choices=[('confirmado', 'Confirmado'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], max_length=12)),
                ('novo', models.CharField(choices=[('confirmado', 'Confirmado'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído')], max_length=12)),
                ('motivo', models.TextField(blank=True, max_length=2000)),
                ('realizado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alteracoes_status', to='agenda.agendamento')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_consultas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alteração de consulta',
                'verbose_name_plural': 'alterações de consultas',
                'ordering': ['-realizado_em', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, max_length=10000, verbose_name='observações da sessão')),
                ('plano_alimentar', models.TextField(blank=True, max_length=10000, verbose_name='plano alimentar')),
                ('orientacoes', models.TextField(blank=True, max_length=10000, verbose_name='orientações e próximos passos')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sessao', to='agenda.agendamento')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_editadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro da sessão',
                'verbose_name_plural': 'registros das sessões',
            },
        ),
        migrations.CreateModel(
            name='MembroEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros_equipe', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_compartilhadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membro da equipe',
                'verbose_name_plural': 'membros da equipe',
                'ordering': ['usuario__username'],
                'constraints': [models.UniqueConstraint(fields=('responsavel', 'usuario'), name='unique_team_member')],
            },
        ),
    ]
